# Generated by Django 2.2.16 on 2022-02-14 14:42

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220213_1217'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='one_love',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='authoe_author',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='one_love'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('following')), name='authoe_author'),
        ),
    ]
